plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'com.opengrid.simplerelationshiptracker'
    compileSdk 35

    defaultConfig {
        applicationId "com.opengrid.simplerelationshiptracker"
        minSdk 26
        targetSdk 36
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        // manifestPlaceholders = [MAPS_API_KEY: "YOUR_API_KEY_HERE"]
    }

    buildTypes {
        release {
            optimization {
                enable false
            }
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    buildFeatures {
        viewBinding true
    }
}

dependencies {
    implementation libs.appcompat
    implementation libs.constraintlayout
    implementation libs.lifecycle.livedata.ktx
    implementation libs.lifecycle.viewmodel.ktx
    implementation libs.material
    implementation libs.navigation.fragment
    implementation libs.navigation.ui
    implementation libs.recyclerview
    implementation libs.retrofit
    implementation libs.converter.gson
    implementation "org.osmdroid:osmdroid-android:6.1.20"
    implementation "com.google.mlkit:translate:17.0.3"
    testImplementation libs.junit
    androidTestImplementation libs.espresso.core
    androidTestImplementation libs.ext.junit
}